format_version: 10
pipelines:
  LiquibasePipeline:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-0da9e2c:
        git: https://github.com/SVanev/quickstart
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - LiquidStage:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            LiquidJob:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - clean
                      - package
                    command: mvn
                    run_if: passed
